version: '3.2'
services:
  sftp:
    image: atmoz/sftp:alpine
    restart: unless-stopped
    volumes:
        - /mnt/data:/home/${SFTP_USER}/data
    ports:
        - "2222:22"
    command: ${SFTP_USER}:${SFTP_PASSWORD}:1001
